package icons

import (
	"path/filepath"
	"strings"

	"github.com/jesseduffield/lazygit/pkg/config"
)

// NOTE: Visit next links for inspiration:
// https://github.com/eza-community/eza/blob/main/src/output/icons.rs
// https://github.com/nvim-tree/nvim-web-devicons/tree/master/lua/nvim-web-devicons/default

var (
	DEFAULT_FILE_ICON      = IconProperties{Icon: "\uf15b", Color: "#cdd6f4	"}     // 
	DEFAULT_SUBMODULE_ICON = IconProperties{Icon: "\U000f02a2", Color: "#FAB387"} // 󰊢
	DEFAULT_DIRECTORY_ICON = IconProperties{Icon: "\uf07b", Color: "#89b4fa	"}     // 
)

// NOTE: The filename map is case sensitive.
var nameIconMap = map[string]IconProperties{
	".atom":                      {Icon: "\ue764", Color: "#F9E2AF"},     // 
	".babelrc":                   {Icon: "\ue639", Color: "#FAB387"},     // 
	".bash_profile":              {Icon: "\ue615", Color: "#A6E3A1"},     // 
	".bashprofile":               {Icon: "\ue615", Color: "#A6E3A1"},     // 
	".bashrc":                    {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".clang-format":              {Icon: "\ue615", Color: "#A6ADC8"},     // 
	".clang-tidy":                {Icon: "\ue615", Color: "#A6ADC8"},     // 
	".codespellrc":               {Icon: "\U000f04c6", Color: "#A6E3A1"}, // 󰓆
	".condarc":                   {Icon: "\ue715", Color: "#A6E3A1"},     // 
	".dockerignore":              {Icon: "\U000f0868", Color: "#74C7EC"}, // 󰡨
	".ds_store":                  {Icon: "\uf302", Color: "#A6ADC8"},     // 
	".editorconfig":              {Icon: "\ue652", Color: "#F5E0DC"},     // 
	".env":                       {Icon: "\U000f066a", Color: "#FAB387"}, // 󰙪
	".eslintignore":              {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	".eslintrc":                  {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	".git":                       {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".git-blame-ignore-revs":     {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".gitattributes":             {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".gitconfig":                 {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".github":                    {Icon: "\uf408", Color: "#A6ADC8"},     // 
	".gitignore":                 {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".gitlab-ci.yml":             {Icon: "\uf296", Color: "#FAB387"},     // 
	".gitmodules":                {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".gtkrc-2.0":                 {Icon: "\uf362", Color: "#F5E0DC"},     // 
	".gvimrc":                    {Icon: "\ue62b", Color: "#A6E3A1"},     // 
	".idea":                      {Icon: "\ue7b5", Color: "#A6ADC8"},     // 
	".justfile":                  {Icon: "\uf0ad", Color: "#A6ADC8"},     // 
	".luacheckrc":                {Icon: "\ue615", Color: "#A6ADC8"},     // 
	".luaurc":                    {Icon: "\ue615", Color: "#74C7EC"},     // 
	".mailmap":                   {Icon: "\U000f01ee", Color: "#74C7EC"}, // 󰇮
	".nanorc":                    {Icon: "\ue838", Color: "#A6ADC8"},     // 
	".npmignore":                 {Icon: "\ued0e", Color: "#F38BA8"},     // 
	".npmrc":                     {Icon: "\ued0e", Color: "#F38BA8"},     // 
	".nuxtrc":                    {Icon: "\U000f1106", Color: "#74C7EC"}, // 󱄆
	".nvmrc":                     {Icon: "\ued0d", Color: "#A6E3A1"},     // 
	".pre-commit-config.yaml":    {Icon: "\U000f06e2", Color: "#FAB387"}, // 󰛢
	".prettierignore":            {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc":                {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc.json":           {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc.json5":          {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc.toml":           {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc.yaml":           {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".prettierrc.yml":            {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	".pylintrc":                  {Icon: "\ue615", Color: "#A6ADC8"},     // 
	".rvm":                       {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".settings.json":             {Icon: "\ue70c", Color: "#A6ADC8"},     // 
	".SRCINFO":                   {Icon: "\uf129", Color: "#74C7EC"},     // 
	".tmux.conf":                 {Icon: "\uebc8", Color: "#A6E3A1"},     // 
	".tmux.conf.local":           {Icon: "\uebc8", Color: "#A6E3A1"},     // 
	".Trash":                     {Icon: "\uf1f8", Color: "#B4BEFE"},     // 
	".vimrc":                     {Icon: "\ue62b", Color: "#A6E3A1"},     // 
	".vscode":                    {Icon: "\ue70c", Color: "#74C7EC"},     // 
	".Xauthority":                {Icon: "\uf369", Color: "#FAB387"},     // 
	".Xresources":                {Icon: "\uf369", Color: "#FAB387"},     // 
	".xinitrc":                   {Icon: "\uf369", Color: "#FAB387"},     // 
	".xsession":                  {Icon: "\uf369", Color: "#FAB387"},     // 
	".zprofile":                  {Icon: "\ue615", Color: "#A6E3A1"},     // 
	".zshenv":                    {Icon: "\ue615", Color: "#A6E3A1"},     // 
	".zshrc":                     {Icon: "\ue795", Color: "#A6E3A1"},     // 
	"_gvimrc":                    {Icon: "\ue62b", Color: "#A6E3A1"},     // 
	"_vimrc":                     {Icon: "\ue62b", Color: "#A6E3A1"},     // 
	"AUTHORS":                    {Icon: "\uedca", Color: "#CBA6F7"},     // 
	"AUTHORS.txt":                {Icon: "\uedca", Color: "#CBA6F7"},     // 
	"bin":                        {Icon: "\U000f12a7", Color: "#74C7EC"}, // 󱊧
	"brewfile":                   {Icon: "\ue791", Color: "#F38BA8"},     // 
	"bspwmrc":                    {Icon: "\uf355", Color: "#A6ADC8"},     // 
	"BUILD":                      {Icon: "\ue63a", Color: "#A6E3A1"},     // 
	"build.gradle":               {Icon: "\ue660", Color: "#74C7EC"},     // 
	"build.zig.zon":              {Icon: "\ue6a9", Color: "#FAB387"},     // 
	"bun.lockb":                  {Icon: "\ue76f", Color: "#F5E0DC"},     // 
	"cantorrc":                   {Icon: "\uf373", Color: "#74C7EC"},     // 
	"Cargo.lock":                 {Icon: "\ue7a8", Color: "#FAB387"},     // 
	"Cargo.toml":                 {Icon: "\ue7a8", Color: "#FAB387"},     // 
	"checkhealth":                {Icon: "\U000f04d9", Color: "#89B4FA"}, // 󰓙
	"CMakeLists.txt":             {Icon: "\ue794", Color: "#CDD6F4"},     // 
	"CODE_OF_CONDUCT":            {Icon: "\uf4ae", Color: "#F38BA8"},     // 
	"CODE_OF_CONDUCT.md":         {Icon: "\uf4ae", Color: "#F38BA8"},     // 
	"CODE-OF-CONDUCT.md":         {Icon: "\uf4ae", Color: "#F38BA8"},     // 
	"commit_editmsg":             {Icon: "\ue702", Color: "#FAB387"},     // 
	"COMMIT_EDITMSG":             {Icon: "\ue702", Color: "#FAB387"},     // 
	"commitlint.config.js":       {Icon: "\U000f0718", Color: "#74C7EC"}, // 
	"commitlint.config.ts":       {Icon: "\U000f0718", Color: "#74C7EC"}, // 
	"compose.yaml":               {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"compose.yml":                {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"config":                     {Icon: "\uf013", Color: "#A6ADC8"},     // 
	"containerfile":              {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"copying":                    {Icon: "\U000f0124", Color: "#FAB387"}, // 󰄤
	"copying.lesser":             {Icon: "\ue60a", Color: "#FAB387"},     // 
	"docker-compose.yaml":        {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"docker-compose.yml":         {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"dockerfile":                 {Icon: "\uf21f", Color: "#74C7EC"},     // 
	"Dockerfile":                 {Icon: "\uf308", Color: "#74C7EC"},     // 
	"ds_store":                   {Icon: "\uf179", Color: "#F5E0DC"},     // 
	"eslint.config.cjs":          {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	"eslint.config.js":           {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	"eslint.config.mjs":          {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	"eslint.config.ts":           {Icon: "\U000f0c7a", Color: "#A6ADC8"}, // 󰱺
	"ext_typoscript_setup.txt":   {Icon: "\ue772", Color: "#FAB387"},     // 
	"favicon.ico":                {Icon: "\ue623", Color: "#FAB387"},     // 
	"fp-info-cache":              {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	"fp-lib-table":               {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	"FreeCAD.conf":               {Icon: "\uf336", Color: "#F38BA8"},     // 
	"gemfile$":                   {Icon: "\ue791", Color: "#F38BA8"},     // 
	"gitignore_global":           {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	"gnumakefile":                {Icon: "\ueba2", Color: "#F38BA8"},     // 
	"GNUmakefile":                {Icon: "\ue779", Color: "#A6ADC8"},     // 
	"go.mod":                     {Icon: "\ue627", Color: "#74C7EC"},     // 
	"go.sum":                     {Icon: "\ue627", Color: "#74C7EC"},     // 
	"go.work":                    {Icon: "\ue627", Color: "#74C7EC"},     // 
	"gradle":                     {Icon: "\ue660", Color: "#74C7EC"},     // 
	"gradle-wrapper.properties":  {Icon: "\ue660", Color: "#74C7EC"},     // 
	"gradle.properties":          {Icon: "\ue660", Color: "#74C7EC"},     // 
	"gradlew":                    {Icon: "\ue660", Color: "#74C7EC"},     // 
	"gruntfile.babel.js":         {Icon: "\ue611", Color: "#FAB387"},     // 
	"gruntfile.coffee":           {Icon: "\ue611", Color: "#FAB387"},     // 
	"gruntfile.js":               {Icon: "\ue611", Color: "#FAB387"},     // 
	"gruntfile.ls":               {Icon: "\ue611", Color: "#FAB387"},     // 
	"gruntfile.ts":               {Icon: "\ue611", Color: "#FAB387"},     // 
	"gtkrc":                      {Icon: "\uf362", Color: "#F5E0DC"},     // 
	"gulpfile.babel.js":          {Icon: "\ue610", Color: "#F38BA8"},     // 
	"gulpfile.coffee":            {Icon: "\ue610", Color: "#F38BA8"},     // 
	"gulpfile.js":                {Icon: "\ue610", Color: "#F38BA8"},     // 
	"gulpfile.ls":                {Icon: "\ue610", Color: "#F38BA8"},     // 
	"gulpfile.ts":                {Icon: "\ue610", Color: "#F38BA8"},     // 
	"hidden":                     {Icon: "\uf023", Color: "#A6ADC8"},     // 
	"hypridle.conf":              {Icon: "\uf359", Color: "#74C7EC"},     // 
	"hyprland.conf":              {Icon: "\uf359", Color: "#74C7EC"},     // 
	"hyprlock.conf":              {Icon: "\uf359", Color: "#74C7EC"},     // 
	"hyprpaper.conf":             {Icon: "\uf359", Color: "#74C7EC"},     // 
	"i3blocks.conf":              {Icon: "\uf35a", Color: "#F5E0DC"},     // 
	"i3status.conf":              {Icon: "\uf35a", Color: "#F5E0DC"},     // 
	"include":                    {Icon: "\ue5fc", Color: "#F5E0DC"},     // 
	"index.theme":                {Icon: "\uee72", Color: "#A6E3A1"},     // 
	"ionic.config.json":          {Icon: "\ue66b", Color: "#74C7EC"},     // 
	"justfile":                   {Icon: "\uf0ad", Color: "#A6ADC8"},     // 
	"kalgebrarc":                 {Icon: "\uf373", Color: "#74C7EC"},     // 
	"kdeglobals":                 {Icon: "\uf373", Color: "#74C7EC"},     // 
	"kdenlive-layoutsrc":         {Icon: "\uf33c", Color: "#89B4FA"},     // 
	"kdenliverc":                 {Icon: "\uf33c", Color: "#89B4FA"},     // 
	"kritadisplayrc":             {Icon: "\uf33d", Color: "#CBA6F7"},     // 
	"kritarc":                    {Icon: "\uf33d", Color: "#CBA6F7"},     // 
	"lib":                        {Icon: "\U000f1517", Color: "#A6E3A1"}, // 󱔗
	"LICENSE":                    {Icon: "\uf02d", Color: "#F5E0DC"},     // 
	"LICENSE.md":                 {Icon: "\uf02d", Color: "#F5E0DC"},     // 
	"localized":                  {Icon: "\uf179", Color: "#F5E0DC"},     // 
	"lxde-rc.xml":                {Icon: "\uf363", Color: "#A6ADC8"},     // 
	"lxqt.conf":                  {Icon: "\uf364", Color: "#74C7EC"},     // 
	"Makefile":                   {Icon: "\ue673", Color: "#F5E0DC"},     // 
	"mix.lock":                   {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	"mpv.conf":                   {Icon: "\uf36e", Color: "#A6ADC8"},     // 
	"node_modules":               {Icon: "\ue718", Color: "#F38BA8"},     // 
	"npmignore":                  {Icon: "\ue71e", Color: "#F38BA8"},     // 
	"nuxt.config.cjs":            {Icon: "\U000f1106", Color: "#74C7EC"}, // 󱄆
	"nuxt.config.js":             {Icon: "\U000f1106", Color: "#74C7EC"}, // 󱄆
	"nuxt.config.mjs":            {Icon: "\U000f1106", Color: "#74C7EC"}, // 󱄆
	"nuxt.config.ts":             {Icon: "\U000f1106", Color: "#74C7EC"}, // 󱄆
	"package-lock.json":          {Icon: "\ued0d", Color: "#F38BA8"},     // 
	"package.json":               {Icon: "\ued0d", Color: "#A6E3A1"},     // 
	"PKGBUILD":                   {Icon: "\uf303", Color: "#74C7EC"},     // 
	"platformio.ini":             {Icon: "\ue682", Color: "#FAB387"},     // 
	"pom.xml":                    {Icon: "\U000f06d3", Color: "#FAB387"}, // 󰛓
	"prettier.config.cjs":        {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	"prettier.config.js":         {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	"prettier.config.mjs":        {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	"prettier.config.ts":         {Icon: "\ue6b4", Color: "#74C7EC"},     // 
	"PrusaSlicer.ini":            {Icon: "\uf351", Color: "#FAB387"},     // 
	"PrusaSlicerGcodeViewer.ini": {Icon: "\uf351", Color: "#FAB387"},     // 
	"py.typed":                   {Icon: "\ue606", Color: "#FAB387"},     // 
	"QtProject.conf":             {Icon: "\uf375", Color: "#A6E3A1"},     // 
	"R":                          {Icon: "\U000f07d4", Color: "#74C7EC"}, // 󰟔
	"README":                     {Icon: "\uf4ed", Color: "#F9E2AF"}, // 
	"README.md":                  {Icon: "\uf4ed", Color: "#F9E2AF"}, // 
	"robots.txt":                 {Icon: "\U000f06a9", Color: "#A6ADC8"}, // 󰚩
	"rubydoc":                    {Icon: "\ue73b", Color: "#F38BA8"},     // 
	"SECURITY":                   {Icon: "\U000f0483", Color: "#BAC2DE"}, // 󰒃
	"SECURITY.md":                {Icon: "\U000f0483", Color: "#BAC2DE"}, // 󰒃
	"settings.gradle":            {Icon: "\ue660", Color: "#74C7EC"},     // 
	"svelte.config.js":           {Icon: "\ue697", Color: "#FAB387"},     // 
	"sxhkdrc":                    {Icon: "\uf355", Color: "#A6ADC8"},     // 
	"sym-lib-table":              {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	"tailwind.config.js":         {Icon: "\U000f13ff", Color: "#74C7EC"}, // 󱏿
	"tailwind.config.mjs":        {Icon: "\U000f13ff", Color: "#74C7EC"}, // 󱏿
	"tailwind.config.ts":         {Icon: "\U000f13ff", Color: "#74C7EC"}, // 󱏿
	"tmux.conf":                  {Icon: "\uebc8", Color: "#A6E3A1"},     // 
	"tmux.conf.local":            {Icon: "\uebc8", Color: "#A6E3A1"},     // 
	"tsconfig.json":              {Icon: "\ue628", Color: "#74C7EC"},     // 
	"unlicense":                  {Icon: "\ue60a", Color: "#FAB387"},     // 
	"vagrantfile$":               {Icon: "\uf2b8", Color: "#74C7EC"},     // 
	"vlcrc":                      {Icon: "\U000f057c", Color: "#FAB387"}, // 󰕼
	"webpack":                    {Icon: "\U000f072b", Color: "#74C7EC"}, // 󰜫
	"weston.ini":                 {Icon: "\uf367", Color: "#FAB387"},     // 
	"WORKSPACE":                  {Icon: "\ue63a", Color: "#A6E3A1"},     // 
	"WORKSPACE.bzlmod":           {Icon: "\ue63a", Color: "#A6E3A1"},     // 
	"xmobarrc":                   {Icon: "\uf35e", Color: "#F38BA8"},     // 
	"xmobarrc.hs":                {Icon: "\uf35e", Color: "#F38BA8"},     // 
	"xmonad.hs":                  {Icon: "\uf35e", Color: "#F38BA8"},     // 
	"xorg.conf":                  {Icon: "\uf369", Color: "#FAB387"},     // 
	"xsettingsd.conf":            {Icon: "\uf369", Color: "#FAB387"},     // 
	"yarn.lock":                  {Icon: "\ue6a7", Color: "#74C7EC"},     // 
}

var extIconMap = map[string]IconProperties{
	".3gp":            {Icon: "\uf03d", Color: "#FAB387"},     // 
	".3mf":            {Icon: "\U000f01a7", Color: "#A6ADC8"}, // 󰆧
	".7z":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".DS_store":       {Icon: "\uf179", Color: "#A6ADC8"},     // 
	".a":              {Icon: "\U000f1517", Color: "#A6E3A1"}, // 󱔗
	".aac":            {Icon: "\uf001", Color: "#74C7EC"},     // 
	".adb":            {Icon: "\ue6b5", Color: "#74C7EC"},     // 
	".ads":            {Icon: "\ue6b5", Color: "#74C7EC"},     // 
	".ai":             {Icon: "\ue7b4", Color: "#FAB387"},     // 
	".aif":            {Icon: "\uf001", Color: "#74C7EC"},     // 
	".aiff":           {Icon: "\U000f0386", Color: "#F38BA8"}, // 󰎆
	".android":        {Icon: "\ue70e", Color: "#A6E3A1"},     // 
	".ape":            {Icon: "\uf001", Color: "#74C7EC"},     // 
	".apk":            {Icon: "\ue70e", Color: "#A6E3A1"},     // 
	".app":            {Icon: "\ueae8", Color: "#F38BA8"},     // 
	".apple":          {Icon: "\ue635", Color: "#A6ADC8"},     // 
	".applescript":    {Icon: "\uf302", Color: "#A6ADC8"},     // 
	".asc":            {Icon: "\U000f0306", Color: "#74C7EC"}, // 󰌆
	".asm":            {Icon: "\ue637", Color: "#74C7EC"},     // 
	".ass":            {Icon: "\U000f0a16", Color: "#FAB387"}, // 󰨖
	".astro":          {Icon: "\ue6b3", Color: "#FAB387"},     // 
	".avi":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".avif":           {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".avro":           {Icon: "\ue60b", Color: "#FAB387"},     // 
	".awk":            {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".azcli":          {Icon: "\uebd8", Color: "#74C7EC"},     // 
	".bak":            {Icon: "\U000f006f", Color: "#A6ADC8"}, // 󰁯
	".bash":           {Icon: "\uebca", Color: "#FAB387"},     // 
	".bash_history":   {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".bash_profile":   {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".bashrc":         {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".bat":            {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".bats":           {Icon: "\U000f0b5f", Color: "#BAC2DE"}, // 󰭟
	".bazel":          {Icon: "\ue63a", Color: "#A6E3A1"},     // 
	".bib":            {Icon: "\U000f1517", Color: "#A6E3A1"}, // 󱔗
	".bicep":          {Icon: "\U000f0fd7", Color: "#FAB387"}, // 󰿗
	".bicepparam":     {Icon: "\ue63b", Color: "#A6ADC8"},     // 
	".blade.php":      {Icon: "\uf2f7", Color: "#F38BA8"},     // 
	".blend":          {Icon: "\U000f00ab", Color: "#FAB387"}, // 󰂫
	".blp":            {Icon: "\U000f0ebe", Color: "#74C7EC"}, // 󰺾
	".bmp":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".brep":           {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".bz":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".bz2":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".bz3":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".bzl":            {Icon: "\ue63a", Color: "#A6E3A1"},     // 
	".c":              {Icon: "\ue61e", Color: "#74C7EC"},     // 
	".c++":            {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".cab":            {Icon: "\ue70f", Color: "#A6ADC8"},     // 
	".cache":          {Icon: "\uf49b", Color: "#F5E0DC"},     // 
	".cast":           {Icon: "\uf03d", Color: "#FAB387"},     // 
	".cbl":            {Icon: "\u2699", Color: "#74C7EC"},     // ⚙
	".cc":             {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".ccm":            {Icon: "\ue61d", Color: "#F38BA8"},     // 
	".cfg":            {Icon: "\uf013", Color: "#74C7EC"},     // 
	".cjs":            {Icon: "\ue60c", Color: "#FAB387"},     // 
	".class":          {Icon: "\uf0f4", Color: "#74C7EC"},     // 
	".clj":            {Icon: "\ue642", Color: "#74C7EC"},     // 
	".cljc":           {Icon: "\ue642", Color: "#74C7EC"},     // 
	".cljd":           {Icon: "\ue76a", Color: "#74C7EC"},     // 
	".cljs":           {Icon: "\ue642", Color: "#74C7EC"},     // 
	".cls":            {Icon: "\ue69b", Color: "#A6ADC8"},     // 
	".cmake":          {Icon: "\ue794", Color: "#CDD6F4"},     // 
	".cmd":            {Icon: "\uebc4", Color: "#FAB387"},     // 
	".cob":            {Icon: "\u2699", Color: "#74C7EC"},     // ⚙
	".cobol":          {Icon: "\u2699", Color: "#74C7EC"},     // ⚙
	".coffee":         {Icon: "\ue61b", Color: "#A6ADC8"},     // 
	".conda":          {Icon: "\ue715", Color: "#A6E3A1"},     // 
	".conf":           {Icon: "\uf013", Color: "#A6ADC8"},     // 
	".config.ru":      {Icon: "\ue791", Color: "#F38BA8"},     // 
	".cp":             {Icon: "\ue646", Color: "#74C7EC"},     // 
	".cpio":           {Icon: "\uf410", Color: "#FAB387"},     // 
	".cpp":            {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".cppm":           {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".cpy":            {Icon: "\u2699", Color: "#74C7EC"},     // ⚙
	".cr":             {Icon: "\ue62f", Color: "#CDD6F4"},     // 
	".crdownload":     {Icon: "\uf019", Color: "#74C7EC"},     // 
	".cs":             {Icon: "\U000f031b", Color: "#74C7EC"}, // 󰌛
	".csh":            {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".cshtml":         {Icon: "\uf486", Color: "#74C7EC"},     // 
	".cson":           {Icon: "\ue61b", Color: "#A6ADC8"},     // 
	".csproj":         {Icon: "\U000f0610", Color: "#F38BA8"}, // 󰘐
	".css":            {Icon: "\ue749", Color: "#74C7EC"},     // 
	".csv":            {Icon: "\U000f021b", Color: "#A6E3A1"}, // 󰈛
	".csx":            {Icon: "\U000f031b", Color: "#74C7EC"}, // 󰌛
	".cts":            {Icon: "\ue628", Color: "#74C7EC"},     // 
	".cu":             {Icon: "\ue64b", Color: "#A6E3A1"},     // 
	".cue":            {Icon: "\U000f0cb9", Color: "#EBA0AC"}, // 󰲹
	".cuh":            {Icon: "\ue64b", Color: "#A6ADC8"},     // 
	".cxx":            {Icon: "\ue646", Color: "#74C7EC"},     // 
	".cxxm":           {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".d":              {Icon: "\ue7af", Color: "#F38BA8"},     // 
	".d.ts":           {Icon: "\ue628", Color: "#74C7EC"},     // 
	".dart":           {Icon: "\ue64c", Color: "#74C7EC"},     // 
	".db":             {Icon: "\uf1c0", Color: "#FAB387"},     // 
	".dconf":          {Icon: "\ue706", Color: "#F5E0DC"},     // 
	".deb":            {Icon: "\uebc5", Color: "#F38BA8"},     // 
	".desktop":        {Icon: "\uf108", Color: "#A6ADC8"},     // 
	".diff":           {Icon: "\uf4d2", Color: "#A6ADC8"},     // 
	".djvu":           {Icon: "\uf02d", Color: "#A6ADC8"},     // 
	".dll":            {Icon: "\U000f107c", Color: "#74C7EC"}, // 󱁼
	".doc":            {Icon: "\U000f022c", Color: "#74C7EC"}, // 󰈬
	".docx":           {Icon: "\U000f022c", Color: "#74C7EC"}, // 󰈬
	".dot":            {Icon: "\U000f1049", Color: "#74C7EC"}, // 󱁉
	".download":       {Icon: "\uf019", Color: "#74C7EC"},     // 
	".drl":            {Icon: "\ue28c", Color: "#EBA0AC"},     // 
	".dropbox":        {Icon: "\ue707", Color: "#89B4FA"},     // 
	".ds_store":       {Icon: "\uf179", Color: "#A6ADC8"},     // 
	".dump":           {Icon: "\uf1c0", Color: "#F5E0DC"},     // 
	".dwg":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".dxf":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".ebook":          {Icon: "\ue28b", Color: "#FAB387"},     // 
	".ebuild":         {Icon: "\uf30d", Color: "#A6ADC8"},     // 
	".editorconfig":   {Icon: "\ue615", Color: "#A6ADC8"},     // 
	".edn":            {Icon: "\ue76a", Color: "#74C7EC"},     // 
	".eex":            {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	".ejs":            {Icon: "\ue618", Color: "#FAB387"},     // 
	".el":             {Icon: "\ue632", Color: "#A6ADC8"},     // 
	".elc":            {Icon: "\ue632", Color: "#A6ADC8"},     // 
	".elf":            {Icon: "\ueae8", Color: "#F38BA8"},     // 
	".elm":            {Icon: "\ue62c", Color: "#74C7EC"},     // 
	".eln":            {Icon: "\ue632", Color: "#A6ADC8"},     // 
	".env":            {Icon: "\uf462", Color: "#FAB387"},     // 
	".eot":            {Icon: "\ue659", Color: "#F38BA8"},     // 
	".epp":            {Icon: "\ue631", Color: "#FAB387"},     // 
	".epub":           {Icon: "\ue28b", Color: "#FAB387"},     // 
	".erb":            {Icon: "\U000f0d2d", Color: "#F38BA8"}, // 󰴭
	".erl":            {Icon: "\uf23f", Color: "#F38BA8"},     // 
	".ex":             {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	".exe":            {Icon: "\uf2d0", Color: "#FAB387"},     // 
	".exs":            {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	".f#":             {Icon: "\ue7a7", Color: "#74C7EC"},     // 
	".f3d":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".f90":            {Icon: "\U000f121a", Color: "#FAB387"}, // 󱈚
	".fbx":            {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".fcbak":          {Icon: "\uf336", Color: "#A6ADC8"},     // 
	".fcmacro":        {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fcmat":          {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fcparam":        {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fcscript":       {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fcstd":          {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fcstd1":         {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fctb":           {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fctl":           {Icon: "\uf336", Color: "#F38BA8"},     // 
	".fdmdownload":    {Icon: "\uf019", Color: "#74C7EC"},     // 
	".fish":           {Icon: "\U000f023a", Color: "#FAB387"}, // 󰈺
	".flac":           {Icon: "\U000f0386", Color: "#F38BA8"}, // 󰎆
	".flc":            {Icon: "\uf031", Color: "#F5E0DC"},     // 
	".flf":            {Icon: "\uf031", Color: "#F5E0DC"},     // 
	".flv":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".fnl":            {Icon: "\ue6af", Color: "#F5E0DC"},     // 
	".fodg":           {Icon: "\uf379", Color: "#FAB387"},     // 
	".fodp":           {Icon: "\uf37a", Color: "#FAB387"},     // 
	".fods":           {Icon: "\uf378", Color: "#A6E3A1"},     // 
	".fodt":           {Icon: "\uf37c", Color: "#74C7EC"},     // 
	".font":           {Icon: "\ue659", Color: "#F38BA8"},     // 
	".fs":             {Icon: "\ue7a7", Color: "#74C7EC"},     // 
	".fsi":            {Icon: "\ue7a7", Color: "#74C7EC"},     // 
	".fsscript":       {Icon: "\ue7a7", Color: "#74C7EC"},     // 
	".fsx":            {Icon: "\ue7a7", Color: "#74C7EC"},     // 
	".gcode":          {Icon: "\U000f0af4", Color: "#A6ADC8"}, // 󰫴
	".gd":             {Icon: "\ue65f", Color: "#74C7EC"},     // 
	".gdoc":           {Icon: "\uf1c2", Color: "#A6E3A1"},     // 
	".gem":            {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".gemfile":        {Icon: "\ueb48", Color: "#F38BA8"},     // 
	".gemspec":        {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".gform":          {Icon: "\uf298", Color: "#A6E3A1"},     // 
	".gif":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".git":            {Icon: "\U000f02a2", Color: "#FAB387"}, // 󰊢
	".glb":            {Icon: "\uf1b2", Color: "#FAB387"},     // 
	".gnumakefile":    {Icon: "\ueba2", Color: "#F38BA8"},     // 
	".go":             {Icon: "\ue627", Color: "#74C7EC"},     // 
	".godot":          {Icon: "\ue65f", Color: "#74C7EC"},     // 
	".gpr":            {Icon: "\ue6b5", Color: "#74C7EC"},     // 
	".gql":            {Icon: "\U000f0877", Color: "#F38BA8"}, // 󰡷
	".gradle":         {Icon: "\ue660", Color: "#74C7EC"},     // 
	".graphql":        {Icon: "\U000f0877", Color: "#F38BA8"}, // 󰡷
	".gresource":      {Icon: "\uf362", Color: "#F5E0DC"},     // 
	".groovy":         {Icon: "\ue775", Color: "#74C7EC"},     // 
	".gsheet":         {Icon: "\uf1c3", Color: "#A6E3A1"},     // 
	".gslides":        {Icon: "\uf1c4", Color: "#FAB387"},     // 
	".guardfile":      {Icon: "\ue21e", Color: "#A6ADC8"},     // 
	".gv":             {Icon: "\U000f1049", Color: "#74C7EC"}, // 󱁉
	".gz":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".h":              {Icon: "\uf0fd", Color: "#A6ADC8"},     // 
	".haml":           {Icon: "\ue664", Color: "#FAB387"},     // 
	".hbs":            {Icon: "\U000f15de", Color: "#FAB387"}, // 󱗞
	".hc":             {Icon: "\U000f00a2", Color: "#FAB387"}, // 󰂢
	".heex":           {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	".hex":            {Icon: "\U000f12a7", Color: "#74C7EC"}, // 󱊧
	".hh":             {Icon: "\uf0fd", Color: "#A6ADC8"},     // 
	".hpp":            {Icon: "\uf0fd", Color: "#A6ADC8"},     // 
	".hrl":            {Icon: "\ue7b1", Color: "#F38BA8"},     // 
	".hs":             {Icon: "\ue61f", Color: "#FAB387"},     // 
	".htm":            {Icon: "\uf13b", Color: "#FAB387"},     // 
	".html":           {Icon: "\uf13b", Color: "#FAB387"},     // 
	".huff":           {Icon: "\U000f0858", Color: "#CDD6F4"}, // 󰡘
	".hurl":           {Icon: "\uf0ec", Color: "#F38BA8"},     // 
	".hx":             {Icon: "\ue666", Color: "#FAB387"},     // 
	".hxx":            {Icon: "\uf0fd", Color: "#A6ADC8"},     // 
	".ical":           {Icon: "\uf073", Color: "#74C7EC"},     // 
	".icalendar":      {Icon: "\uf073", Color: "#74C7EC"},     // 
	".ico":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".ics":            {Icon: "\U000f01ee", Color: "#74C7EC"}, // 󰇮
	".ifb":            {Icon: "\uf073", Color: "#74C7EC"},     // 
	".ifc":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".ige":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".iges":           {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".igs":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".image":          {Icon: "\uf1c5", Color: "#FAB387"},     // 
	".img":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".iml":            {Icon: "\U000f022e", Color: "#A6E3A1"}, // 󰈮
	".import":         {Icon: "\uf0c6", Color: "#F5E0DC"},     // 
	".info":           {Icon: "\uf129", Color: "#F5E0DC"},     // 
	".ini":            {Icon: "\uf013", Color: "#74C7EC"},     // 
	".ino":            {Icon: "\uf34b", Color: "#74C7EC"},     // 
	".ipynb":          {Icon: "\ue80f", Color: "#FAB387"},     // 
	".iso":            {Icon: "\uede9", Color: "#A6ADC8"},     // 
	".ixx":            {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".j2c":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".j2k":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".jad":            {Icon: "\ue256", Color: "#FAB387"},     // 
	".jar":            {Icon: "\U000f06ca", Color: "#FAB387"}, // 󰛊
	".java":           {Icon: "\uf0f4", Color: "#FAB387"},     // 
	".jfi":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".jfif":           {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".jif":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".jl":             {Icon: "\ue624", Color: "#A6E3A1"},     // 
	".jmd":            {Icon: "\uf48a", Color: "#74C7EC"},     // 
	".jp2":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".jpe":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".jpeg":           {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".jpg":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".jpx":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".js":             {Icon: "\U000f031e", Color: "#FAB387"}, // 󰌞
	".json":           {Icon: "\ue60b", Color: "#FAB387"},     // 
	".json5":          {Icon: "\ue60b", Color: "#FAB387"},     // 
	".jsonc":          {Icon: "\ue60b", Color: "#FAB387"},     // 
	".jsx":            {Icon: "\ued46", Color: "#FAB387"},     // 
	".jwmrc":          {Icon: "\uf35b", Color: "#74C7EC"},     // 
	".jxl":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".kbx":            {Icon: "\U000f0bc4", Color: "#A6ADC8"}, // 󰯄
	".kdb":            {Icon: "\uf23e", Color: "#A6E3A1"},     // 
	".kdbx":           {Icon: "\uf23e", Color: "#A6E3A1"},     // 
	".kdenlive":       {Icon: "\uf33c", Color: "#89B4FA"},     // 
	".kdenlivetitle":  {Icon: "\uf33c", Color: "#89B4FA"},     // 
	".kicad_dru":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_mod":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_pcb":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_prl":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_pro":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_sch":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_sym":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".kicad_wks":      {Icon: "\uf34c", Color: "#F5E0DC"},     // 
	".ko":             {Icon: "\uf17c", Color: "#F5E0DC"},     // 
	".kpp":            {Icon: "\uf33d", Color: "#CBA6F7"},     // 
	".kra":            {Icon: "\uf33d", Color: "#CBA6F7"},     // 
	".krz":            {Icon: "\uf33d", Color: "#CBA6F7"},     // 
	".ksh":            {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".kt":             {Icon: "\ue634", Color: "#74C7EC"},     // 
	".kts":            {Icon: "\ue634", Color: "#74C7EC"},     // 
	".latex":          {Icon: "\ue69b", Color: "#A6ADC8"},     // 
	".lck":            {Icon: "\ue672", Color: "#A6ADC8"},     // 
	".leex":           {Icon: "\ue62d", Color: "#A6ADC8"},     // 
	".less":           {Icon: "\ued48", Color: "#74C7EC"},     // 
	".lff":            {Icon: "\uf031", Color: "#F5E0DC"},     // 
	".lhs":            {Icon: "\ue777", Color: "#A6ADC8"},     // 
	".license":        {Icon: "\U000f0124", Color: "#FAB387"}, // 󰄤
	".liquid":         {Icon: "\uf043", Color: "#74C7EC"},     // 
	".localized":      {Icon: "\uf179", Color: "#A6ADC8"},     // 
	".lock":           {Icon: "\uf023", Color: "#FAB387"},     // 
	".log":            {Icon: "\uf0f6", Color: "#FAB387"},     // 
	".lrc":            {Icon: "\U000f0a16", Color: "#FAB387"}, // 󰨖
	".lua":            {Icon: "\ue620", Color: "#74C7EC"},     // 
	".luac":           {Icon: "\ue620", Color: "#74C7EC"},     // 
	".luau":           {Icon: "\ue620", Color: "#74C7EC"},     // 
	".lz":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".lz4":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".lzh":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".lzma":           {Icon: "\uf410", Color: "#FAB387"},     // 
	".lzo":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".m":              {Icon: "\ue61e", Color: "#74C7EC"},     // 
	".m3u":            {Icon: "\U000f0cb9", Color: "#EBA0AC"}, // 󰲹
	".m3u8":           {Icon: "\U000f0cb9", Color: "#EBA0AC"}, // 󰲹
	".m4a":            {Icon: "\U000f0386", Color: "#F38BA8"}, // 󰎆
	".m4v":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".magnet":         {Icon: "\uf076", Color: "#F38BA8"},     // 
	".makefile":       {Icon: "\ue673", Color: "#F5E0DC"},     // 
	".markdown":       {Icon: "\ueb1d", Color: "#74C7EC"},     // 
	".material":       {Icon: "\U000f0509", Color: "#F38BA8"}, // 󰔉
	".md":             {Icon: "\ueb1d", Color: "#74C7EC"},     // 
	".md5":            {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".mdx":            {Icon: "\ueb1d", Color: "#FAB387"},     // 
	".mint":           {Icon: "\ue7a4", Color: "#A6E3A1"},     // 
	".mjs":            {Icon: "\U000f031e", Color: "#FAB387"}, // 󰌞
	".mk":             {Icon: "\ue795", Color: "#A6ADC8"},     // 
	".mkd":            {Icon: "\uf48a", Color: "#74C7EC"},     // 
	".mkv":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".ml":             {Icon: "\ue67a", Color: "#FAB387"},     // 
	".mli":            {Icon: "\ue67a", Color: "#FAB387"},     // 
	".mm":             {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".mo":             {Icon: "\U000f05ca", Color: "#A6ADC8"}, // 󰗊
	".mobi":           {Icon: "\ue28b", Color: "#FAB387"},     // 
	".mojo":           {Icon: "\ue780", Color: "#FAB387"},     // 
	".mov":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".mp3":            {Icon: "\U000f0386", Color: "#F38BA8"}, // 󰎆
	".mp4":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".mpp":            {Icon: "\ue61d", Color: "#74C7EC"},     // 
	".msf":            {Icon: "\uf370", Color: "#74C7EC"},     // 
	".msi":            {Icon: "\uf2d0", Color: "#FAB387"},     // 
	".mts":            {Icon: "\ue628", Color: "#74C7EC"},     // 
	".mustache":       {Icon: "\U000f15de", Color: "#FAB387"}, // 󱗞
	".nfo":            {Icon: "\uf129", Color: "#F5E0DC"},     // 
	".nim":            {Icon: "\ue677", Color: "#FAB387"},     // 
	".nix":            {Icon: "\uf313", Color: "#74C7EC"},     // 
	".node":           {Icon: "\U000f0399", Color: "#F38BA8"}, // 󰎙
	".npmignore":      {Icon: "\ue71e", Color: "#F38BA8"},     // 
	".nswag":          {Icon: "\ue60b", Color: "#A6E3A1"},     // 
	".nu":             {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".o":              {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".obj":            {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".odin":           {Icon: "\U000f07e2", Color: "#74C7EC"}, // 󰟢
	".odf":            {Icon: "\uf37b", Color: "#F38BA8"},     // 
	".odg":            {Icon: "\uf379", Color: "#FAB387"},     // 
	".odp":            {Icon: "\uf37a", Color: "#FAB387"},     // 
	".ods":            {Icon: "\uf378", Color: "#A6E3A1"},     // 
	".odt":            {Icon: "\uf37c", Color: "#74C7EC"},     // 
	".ogg":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".ogv":            {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".opus":           {Icon: "\U000f0223", Color: "#FAB387"}, // 󰈣
	".org":            {Icon: "\ue633", Color: "#74C7EC"},     // 
	".otf":            {Icon: "\ue659", Color: "#F38BA8"},     // 
	".out":            {Icon: "\ueae8", Color: "#F38BA8"},     // 
	".part":           {Icon: "\uf43a", Color: "#A6ADC8"},     // 
	".patch":          {Icon: "\uf440", Color: "#A6ADC8"},     // 
	".pck":            {Icon: "\uf487", Color: "#A6ADC8"},     // 
	".pdf":            {Icon: "\uf1c1", Color: "#F38BA8"},     // 
	".php":            {Icon: "\U000f031f", Color: "#74C7EC"}, // 󰌟
	".pl":             {Icon: "\U000f03d2", Color: "#F38BA8"}, // 󰏒
	".pls":            {Icon: "\U000f0cb9", Color: "#EBA0AC"}, // 󰲹
	".ply":            {Icon: "\U000f01a7", Color: "#A6ADC8"}, // 󰆧
	".pm":             {Icon: "\ue769", Color: "#A6ADC8"},     // 
	".png":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".po":             {Icon: "\U000f05ca", Color: "#A6ADC8"}, // 󰗊
	".pot":            {Icon: "\U000f05ca", Color: "#A6ADC8"}, // 󰗊
	".pp":             {Icon: "\ue631", Color: "#FAB387"},     // 
	".ppt":            {Icon: "\U000f0227", Color: "#F38BA8"}, // 󰈧
	".pptx":           {Icon: "\U000f0227", Color: "#F38BA8"}, // 󰈧
	".prisma":         {Icon: "\ue684", Color: "#74C7EC"},     // 
	".pro":            {Icon: "\U000f03d2", Color: "#F38BA8"}, // 󰏒
	".procfile":       {Icon: "\ue607", Color: "#A6ADC8"},     // 
	".properties":     {Icon: "\uf013", Color: "#74C7EC"},     // 
	".ps1":            {Icon: "\U000f0a0a", Color: "#74C7EC"}, // 󰨊
	".psb":            {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".psd":            {Icon: "\ue7b8", Color: "#74C7EC"},     // 
	".psd1":           {Icon: "\U000f0a0a", Color: "#74C7EC"}, // 󰨊
	".psm1":           {Icon: "\U000f0a0a", Color: "#74C7EC"}, // 󰨊
	".pub":            {Icon: "\U000f0306", Color: "#74C7EC"}, // 󰌆
	".pxd":            {Icon: "\ue606", Color: "#74C7EC"},     // 
	".pxi":            {Icon: "\ue606", Color: "#74C7EC"},     // 
	".pxm":            {Icon: "\uf1c5", Color: "#A6ADC8"},     // 
	".py":             {Icon: "\ued1b", Color: "#FAB387"},     // 
	".pyc":            {Icon: "\ue606", Color: "#FAB387"},     // 
	".pyd":            {Icon: "\ue606", Color: "#FAB387"},     // 
	".pyi":            {Icon: "\ue606", Color: "#FAB387"},     // 
	".pyo":            {Icon: "\ue606", Color: "#FAB387"},     // 
	".pyw":            {Icon: "\ue606", Color: "#74C7EC"},     // 
	".pyx":            {Icon: "\ue606", Color: "#74C7EC"},     // 
	".qm":             {Icon: "\U000f05ca", Color: "#74C7EC"}, // 󰗊
	".qml":            {Icon: "\uf375", Color: "#A6E3A1"},     // 
	".qrc":            {Icon: "\uf375", Color: "#A6E3A1"},     // 
	".qss":            {Icon: "\uf375", Color: "#A6E3A1"},     // 
	".query":          {Icon: "\ue21c", Color: "#A6E3A1"},     // 
	".r":              {Icon: "\ue68a", Color: "#74C7EC"},     // 
	".rake":           {Icon: "\ue791", Color: "#F38BA8"},     // 
	".rakefile":       {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".rar":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".razor":          {Icon: "\uf1fa", Color: "#A6ADC8"},     // 
	".rb":             {Icon: "\U000f0d2d", Color: "#F38BA8"}, // 󰴭
	".rdata":          {Icon: "\uf25d", Color: "#74C7EC"},     // 
	".rdb":            {Icon: "\ue76d", Color: "#F38BA8"},     // 
	".rdoc":           {Icon: "\uf48a", Color: "#74C7EC"},     // 
	".rds":            {Icon: "\uf25d", Color: "#74C7EC"},     // 
	".readme":         {Icon: "\uf05a", Color: "#74C7EC"},     // 
	".res":            {Icon: "\ue688", Color: "#F38BA8"},     // 
	".resi":           {Icon: "\ue688", Color: "#FAB387"},     // 
	".rlib":           {Icon: "\ue7a8", Color: "#FAB387"},     // 
	".rmd":            {Icon: "\ue68a", Color: "#74C7EC"},     // 
	".rpm":            {Icon: "\ue7bb", Color: "#F38BA8"},     // 
	".rproj":          {Icon: "\U000f05c6", Color: "#A6E3A1"}, // 󰗆
	".rs":             {Icon: "\ue68b", Color: "#FAB387"},     // 
	".rspec":          {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".rspec_parallel": {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".rspec_status":   {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".rss":            {Icon: "\uf09e", Color: "#FAB387"},     // 
	".rtf":            {Icon: "\U000f022c", Color: "#74C7EC"}, // 󰈬
	".ru":             {Icon: "\ue21e", Color: "#F38BA8"},     // 
	".rubydoc":        {Icon: "\ue73b", Color: "#F38BA8"},     // 
	".s":              {Icon: "\ue637", Color: "#74C7EC"},     // 
	".sass":           {Icon: "\ue603", Color: "#F38BA8"},     // 
	".sbt":            {Icon: "\ue68d", Color: "#74C7EC"},     // 
	".sc":             {Icon: "\ue68e", Color: "#F38BA8"},     // 
	".scad":           {Icon: "\uf34e", Color: "#FAB387"},     // 
	".scala":          {Icon: "\ue68e", Color: "#F38BA8"},     // 
	".scm":            {Icon: "\U000f0627", Color: "#F38BA8"}, // 󰘧
	".scss":           {Icon: "\ue603", Color: "#F38BA8"},     // 
	".sh":             {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".sha1":           {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".sha224":         {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".sha256":         {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".sha384":         {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".sha512":         {Icon: "\U000f0565", Color: "#A6ADC8"}, // 󰕥
	".shell":          {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".sig":            {Icon: "\u03bb", Color: "#FAB387"},     // Λ
	".signature":      {Icon: "\u03bb", Color: "#FAB387"},     // Λ
	".skp":            {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".sldasm":         {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".sldprt":         {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".slim":           {Icon: "\ue692", Color: "#FAB387"},     // 
	".sln":            {Icon: "\U000f0610", Color: "#F38BA8"}, // 󰘐
	".slvs":           {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".sml":            {Icon: "\u03bb", Color: "#FAB387"},     // Λ
	".so":             {Icon: "\U000f107c", Color: "#74C7EC"}, // 󱁼
	".sol":            {Icon: "\ue656", Color: "#74C7EC"},     // 
	".spec.js":        {Icon: "\uf499", Color: "#FAB387"},     // 
	".spec.jsx":       {Icon: "\uf499", Color: "#FAB387"},     // 
	".spec.ts":        {Icon: "\uf499", Color: "#74C7EC"},     // 
	".spec.tsx":       {Icon: "\uf499", Color: "#74C7EC"},     // 
	".sql":            {Icon: "\uf1c0", Color: "#A6E3A1"},     // 
	".sqlite":         {Icon: "\uf1c0", Color: "#A6E3A1"},     // 
	".sqlite3":        {Icon: "\uf1c0", Color: "#A6E3A1"},     // 
	".srt":            {Icon: "\U000f0a16", Color: "#FAB387"}, // 󰨖
	".ssa":            {Icon: "\U000f0a16", Color: "#FAB387"}, // 󰨖
	".ste":            {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".step":           {Icon: "\U000f0eeb", Color: "#A6E3A1"}, // 󰻫
	".stl":            {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".stp":            {Icon: "\uea8c", Color: "#74C7EC"},     // 
	".strings":        {Icon: "\U000f05ca", Color: "#74C7EC"}, // 󰗊
	".sty":            {Icon: "\ue69b", Color: "#74C7EC"},     // 
	".styl":           {Icon: "\ue759", Color: "#FAB387"},     // 
	".stylus":         {Icon: "\ue600", Color: "#A6E3A1"},     // 
	".sub":            {Icon: "\U000f0a16", Color: "#FAB387"}, // 󰨖
	".sublime":        {Icon: "\ue7aa", Color: "#FAB387"},     // 
	".suo":            {Icon: "\U000f0610", Color: "#F38BA8"}, // 󰘐
	".sv":             {Icon: "\U000f035b", Color: "#FAB387"}, // 󰍛
	".svelte":         {Icon: "\ue697", Color: "#FAB387"},     // 
	".svg":            {Icon: "\U000f0721", Color: "#FAB387"}, // 󰜡
	".svh":            {Icon: "\U000f035b", Color: "#FAB387"}, // 󰍛
	".swift":          {Icon: "\U000f06e5", Color: "#FAB387"}, // 󰛥
	".t":              {Icon: "\ue769", Color: "#74C7EC"},     // 
	".tar":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".taz":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".tbc":            {Icon: "\U000f06d3", Color: "#74C7EC"}, // 󰛓
	".tbz":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".tbz2":           {Icon: "\uf410", Color: "#FAB387"},     // 
	".tcl":            {Icon: "\U000f06d3", Color: "#F38BA8"}, // 󰛓
	".templ":          {Icon: "\U000f05c0", Color: "#FAB387"}, // 󰗀
	".terminal":       {Icon: "\uf489", Color: "#A6E3A1"},     // 
	".test.js":        {Icon: "\uf499", Color: "#FAB387"},     // 
	".test.jsx":       {Icon: "\uf499", Color: "#FAB387"},     // 
	".test.ts":        {Icon: "\uf499", Color: "#74C7EC"},     // 
	".test.tsx":       {Icon: "\uf499", Color: "#74C7EC"},     // 
	".tex":            {Icon: "\ue69b", Color: "#74C7EC"},     // 
	".tf":             {Icon: "\ue69a", Color: "#A6ADC8"},     // 
	".tfvars":         {Icon: "\ue69a", Color: "#A6ADC8"},     // 
	".tgz":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".tiff":           {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".tlz":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".tmux":           {Icon: "\uebc8", Color: "#A6E3A1"},     // 
	".toml":           {Icon: "\ue6b2", Color: "#F38BA8"},     // 
	".torrent":        {Icon: "\ue275", Color: "#74C7EC"},     // 
	".tres":           {Icon: "\ue65f", Color: "#74C7EC"},     // 
	".ts":             {Icon: "\U000f06e6", Color: "#74C7EC"}, // 󰛦
	".tscn":           {Icon: "\ue65f", Color: "#74C7EC"},     // 
	".tsconfig":       {Icon: "\ue772", Color: "#FAB387"},     // 
	".tsv":            {Icon: "\U000f021b", Color: "#A6E3A1"}, // 󰈛
	".tsx":            {Icon: "\ued46", Color: "#74C7EC"},     // 
	".ttf":            {Icon: "\ue659", Color: "#F38BA8"},     // 
	".twig":           {Icon: "\ue61c", Color: "#A6E3A1"},     // 
	".txt":            {Icon: "\U000f0219", Color: "#74C7EC"}, // 󰈙
	".txz":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".typ":            {Icon: "\uf37f", Color: "#74C7EC"},     // 
	".typoscript":     {Icon: "\ue772", Color: "#FAB387"},     // 
	".tz":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".tzo":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".ui":             {Icon: "\uf2d0", Color: "#74C7EC"},     // 
	".v":              {Icon: "\ue6ac", Color: "#74C7EC"},     // 
	".vala":           {Icon: "\ue8d1", Color: "#A6ADC8"},     // 
	".vh":             {Icon: "\U000f035b", Color: "#A6E3A1"}, // 󰍛
	".vhd":            {Icon: "\U000f035b", Color: "#FAB387"}, // 󰍛
	".vhdl":           {Icon: "\U000f035b", Color: "#A6E3A1"}, // 󰍛
	".video":          {Icon: "\uf03d", Color: "#A6ADC8"},     // 
	".vi":             {Icon: "\ue81e", Color: "#FAB387"},     // 
	".vim":            {Icon: "\ue62b", Color: "#A6E3A1"},     // 
	".vsh":            {Icon: "\ue6ac", Color: "#74C7EC"},     // 
	".vsix":           {Icon: "\U000f0a1e", Color: "#74C7EC"}, // 󰨞
	".vue":            {Icon: "\ue6a0", Color: "#A6E3A1"},     // 
	".war":            {Icon: "\ue256", Color: "#F38BA8"},     // 
	".wasm":           {Icon: "\ue6a1", Color: "#89B4FA"},     // 
	".wav":            {Icon: "\U000f0386", Color: "#A6E3A1"}, // 󰎆
	".webm":           {Icon: "\U000f0381", Color: "#FAB387"}, // 󰎁
	".webmanifest":    {Icon: "\ue60b", Color: "#FAB387"},     // 
	".webp":           {Icon: "\U000f021f", Color: "#74C7EC"}, // 󰈟
	".webpack":        {Icon: "\U000f072b", Color: "#74C7EC"}, // 󰜫
	".windows":        {Icon: "\uf17a", Color: "#74C7EC"},     // 
	".wma":            {Icon: "\U000f0386", Color: "#F38BA8"}, // 󰎆
	".woff":           {Icon: "\ue659", Color: "#F38BA8"},     // 
	".woff2":          {Icon: "\ue659", Color: "#F38BA8"},     // 
	".wrl":            {Icon: "\U000f01a7", Color: "#A6ADC8"}, // 󰆧
	".wrz":            {Icon: "\U000f01a7", Color: "#A6ADC8"}, // 󰆧
	".wv":             {Icon: "\uf001", Color: "#74C7EC"},     // 
	".wvc":            {Icon: "\uf001", Color: "#74C7EC"},     // 
	".x":              {Icon: "\ue691", Color: "#74C7EC"},     // 
	".xaml":           {Icon: "\U000f0673", Color: "#74C7EC"}, // 󰙳
	".xcf":            {Icon: "\uf338", Color: "#A6ADC8"},     // 
	".xcplayground":   {Icon: "\ue755", Color: "#FAB387"},     // 
	".xcstrings":      {Icon: "\U000f05ca", Color: "#74C7EC"}, // 󰗊
	".xhtml":          {Icon: "\uf13b", Color: "#FAB387"},     // 
	".xls":            {Icon: "\U000f021b", Color: "#A6E3A1"}, // 󰈛
	".xlsx":           {Icon: "\U000f021b", Color: "#A6E3A1"}, // 󰈛
	".xm":             {Icon: "\ue691", Color: "#74C7EC"},     // 
	".xml":            {Icon: "\U000f022e", Color: "#A6E3A1"}, // 󰈮
	".xpi":            {Icon: "\ueae6", Color: "#A6ADC8"},     // 
	".xul":            {Icon: "\uf121", Color: "#FAB387"},     // 
	".xz":             {Icon: "\uf410", Color: "#FAB387"},     // 
	".yaml":           {Icon: "\ue6a8", Color: "#A6ADC8"},     // 
	".yml":            {Icon: "\ue6a8", Color: "#A6ADC8"},     // 
	".zig":            {Icon: "\ue6a9", Color: "#FAB387"},     // 
	".zip":            {Icon: "\uf410", Color: "#FAB387"},     // 
	".zsh":            {Icon: "\U000f018d", Color: "#FAB387"}, // 󰆍
	".zsh-theme":      {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".zshrc":          {Icon: "\ue795", Color: "#A6E3A1"},     // 
	".zst":            {Icon: "\uf410", Color: "#FAB387"},     // 
}

func patchFileIconsForNerdFontsV2() {
	extIconMap[".cs"] = IconProperties{Icon: "\uf81a", Color: "#F5E0DC"}      // 
	extIconMap[".csproj"] = IconProperties{Icon: "\uf81a", Color: "#F38BA8"}  // 
	extIconMap[".csx"] = IconProperties{Icon: "\uf81a", Color: "#74C7EC"}     // 
	extIconMap[".license"] = IconProperties{Icon: "\uf718", Color: "#A6ADC8"} // 
	extIconMap[".node"] = IconProperties{Icon: "\uf898", Color: "#F38BA8"}    // 
	extIconMap[".rtf"] = IconProperties{Icon: "\uf718", Color: "#A6ADC8"}     // 
	extIconMap[".vue"] = IconProperties{Icon: "\ufd42", Color: "#A6E3A1"}     // ﵂
}

func IconForFile(name string, isSubmodule bool, isLinkedWorktree bool, isDirectory bool, customIconsConfig *config.CustomIconsConfig) IconProperties {
	base := filepath.Base(name)
	if icon, ok := customIconsConfig.Filenames[base]; ok {
		return IconProperties{Color: icon.Color, Icon: icon.Icon}
	}
	if icon, ok := nameIconMap[base]; ok {
		return icon
	}

	ext := strings.ToLower(filepath.Ext(name))
	if icon, ok := customIconsConfig.Extensions[ext]; ok {
		return IconProperties{Color: icon.Color, Icon: icon.Icon}
	}
	if icon, ok := extIconMap[ext]; ok {
		return icon
	}

	if isSubmodule {
		return DEFAULT_SUBMODULE_ICON
	} else if isLinkedWorktree {
		return IconProperties{LINKED_WORKTREE_ICON, "#4E4E4E"}
	} else if isDirectory {
		return DEFAULT_DIRECTORY_ICON
	}
	return DEFAULT_FILE_ICON
}
